<?php
namespace App\Controllers;

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use TCPDF;

class ExportController
{
    private $baseUrl;

    public function __construct()
    {
        $this->baseUrl = "http://localhost/FundiFix-Project/public/index.php";
    }

    // ==================== FUNDI REPORT EXPORTS ====================

    public function exportFundiPDF()
    {
        if (!isset($_SESSION['user']) || $_SESSION['user']['role'] !== 'fundi') {
            header('Location: ' . $this->baseUrl . '?action=login');
            exit;
        }

        $stats = $_SESSION['fundi_stats'] ?? [];
        $userName = $_SESSION['user']['name'];

        // Create PDF
        $pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
        
        // Set document information
        $pdf->SetCreator('FundiFix');
        $pdf->SetAuthor('FundiFix System');
        $pdf->SetTitle('Fundi Performance Report - ' . $userName);
        $pdf->SetSubject('Performance Analytics Report');
        
        // Add a page
        $pdf->AddPage();
        
        // Title
        $pdf->SetFont('helvetica', 'B', 16);
        $pdf->Cell(0, 10, 'Fundi Performance Report', 0, 1, 'C');
        $pdf->SetFont('helvetica', '', 12);
        $pdf->Cell(0, 10, 'Generated for: ' . $userName, 0, 1, 'C');
        $pdf->Cell(0, 10, 'Date: ' . date('F j, Y'), 0, 1, 'C');
        $pdf->Ln(10);

        // Performance Summary
        $pdf->SetFont('helvetica', 'B', 14);
        $pdf->Cell(0, 10, 'Performance Summary', 0, 1);
        $pdf->SetFont('helvetica', '', 12);
        
        $summaryData = [
            'Total Bookings' => $stats['total_bookings'] ?? 0,
            'Completed Jobs' => $stats['completed_bookings'] ?? 0,
            'Pending Requests' => $stats['pending_bookings'] ?? 0,
            'Cancelled Bookings' => $stats['cancelled_bookings'] ?? 0,
            'Total Earnings' => 'KES ' . number_format($stats['total_earnings'] ?? 0, 2),
            'Average Rating' => number_format($stats['average_rating'] ?? 0, 1) . '/5'
        ];

        foreach ($summaryData as $label => $value) {
            $pdf->Cell(80, 8, $label . ':', 0, 0);
            $pdf->Cell(0, 8, $value, 0, 1);
        }

        $pdf->Ln(10);

        // Booking Distribution
        $pdf->SetFont('helvetica', 'B', 14);
        $pdf->Cell(0, 10, 'Booking Distribution', 0, 1);
        $pdf->SetFont('helvetica', '', 12);
        
        $bookingData = [
            'Completed' => $stats['completed_bookings'] ?? 0,
            'Pending' => $stats['pending_bookings'] ?? 0,
            'Cancelled' => $stats['cancelled_bookings'] ?? 0
        ];

        foreach ($bookingData as $status => $count) {
            $percentage = $stats['total_bookings'] > 0 ? 
                round(($count / $stats['total_bookings']) * 100, 1) : 0;
            $pdf->Cell(80, 8, $status . ':', 0, 0);
            $pdf->Cell(0, 8, $count . ' (' . $percentage . '%)', 0, 1);
        }

        // Footer
        $pdf->SetY(-15);
        $pdf->SetFont('helvetica', 'I', 8);
        $pdf->Cell(0, 10, 'Generated by FundiFix - ' . date('Y-m-d H:i:s'), 0, 0, 'C');

        // Output PDF
        $pdf->Output('fundi_report_' . date('Y_m_d') . '.pdf', 'D');
        exit;
    }

    public function exportFundiExcel()
    {
        if (!isset($_SESSION['user']) || $_SESSION['user']['role'] !== 'fundi') {
            header('Location: ' . $this->baseUrl . '?action=login');
            exit;
        }

        $stats = $_SESSION['fundi_stats'] ?? [];
        $userName = $_SESSION['user']['name'];

        // Create new Spreadsheet
        $spreadsheet = new Spreadsheet();
        $sheet = $spreadsheet->getActiveSheet();

        // Set document properties
        $spreadsheet->getProperties()
            ->setCreator('FundiFix')
            ->setTitle('Fundi Performance Report - ' . $userName)
            ->setSubject('Performance Analytics');

        // Set headers
        $sheet->setCellValue('A1', 'Fundi Performance Report');
        $sheet->setCellValue('A2', 'Generated for: ' . $userName);
        $sheet->setCellValue('A3', 'Date: ' . date('F j, Y'));
        
        // Performance Summary
        $sheet->setCellValue('A5', 'Performance Summary');
        $sheet->getStyle('A5')->getFont()->setBold(true);
        
        $summaryData = [
            ['Total Bookings', $stats['total_bookings'] ?? 0],
            ['Completed Jobs', $stats['completed_bookings'] ?? 0],
            ['Pending Requests', $stats['pending_bookings'] ?? 0],
            ['Cancelled Bookings', $stats['cancelled_bookings'] ?? 0],
            ['Total Earnings', 'KES ' . number_format($stats['total_earnings'] ?? 0, 2)],
            ['Average Rating', number_format($stats['average_rating'] ?? 0, 1) . '/5']
        ];

        $row = 6;
        foreach ($summaryData as $data) {
            $sheet->setCellValue('A' . $row, $data[0]);
            $sheet->setCellValue('B' . $row, $data[1]);
            $row++;
        }

        // Booking Distribution
        $row += 2;
        $sheet->setCellValue('A' . $row, 'Booking Distribution');
        $sheet->getStyle('A' . $row)->getFont()->setBold(true);
        $row++;

        $bookingData = [
            ['Status', 'Count', 'Percentage'],
            ['Completed', $stats['completed_bookings'] ?? 0],
            ['Pending', $stats['pending_bookings'] ?? 0],
            ['Cancelled', $stats['cancelled_bookings'] ?? 0]
        ];

        foreach ($bookingData as $data) {
            if ($data[0] === 'Status') {
                $sheet->setCellValue('A' . $row, $data[0]);
                $sheet->setCellValue('B' . $row, $data[1]);
                $sheet->setCellValue('C' . $row, $data[2]);
                $sheet->getStyle('A' . $row . ':C' . $row)->getFont()->setBold(true);
            } else {
                $percentage = $stats['total_bookings'] > 0 ? 
                    round(($data[1] / $stats['total_bookings']) * 100, 1) : 0;
                $sheet->setCellValue('A' . $row, $data[0]);
                $sheet->setCellValue('B' . $row, $data[1]);
                $sheet->setCellValue('C' . $row, $percentage . '%');
            }
            $row++;
        }

        // Auto-size columns
        foreach (range('A', 'C') as $column) {
            $sheet->getColumnDimension($column)->setAutoSize(true);
        }

        // Create Excel file
        $writer = new Xlsx($spreadsheet);
        
        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment;filename="fundi_report_' . date('Y_m_d') . '.xlsx"');
        header('Cache-Control: max-age=0');

        $writer->save('php://output');
        exit;
    }

    // ==================== RESIDENT REPORT EXPORTS ====================

    public function exportResidentPDF()
    {
        if (!isset($_SESSION['user']) || $_SESSION['user']['role'] !== 'resident') {
            header('Location: ' . $this->baseUrl . '?action=login');
            exit;
        }

        $analytics = $_SESSION['resident_analytics'] ?? [];
        $userName = $_SESSION['user']['name'];

        // Create PDF
        $pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
        
        // Set document information
        $pdf->SetCreator('FundiFix');
        $pdf->SetAuthor('FundiFix System');
        $pdf->SetTitle('Resident Service Report - ' . $userName);
        $pdf->SetSubject('Service Usage Report');
        
        // Add a page
        $pdf->AddPage();
        
        // Title
        $pdf->SetFont('helvetica', 'B', 16);
        $pdf->Cell(0, 10, 'Resident Service Report', 0, 1, 'C');
        $pdf->SetFont('helvetica', '', 12);
        $pdf->Cell(0, 10, 'Generated for: ' . $userName, 0, 1, 'C');
        $pdf->Cell(0, 10, 'Date: ' . date('F j, Y'), 0, 1, 'C');
        $pdf->Ln(10);

        // Usage Summary
        $pdf->SetFont('helvetica', 'B', 14);
        $pdf->Cell(0, 10, 'Service Usage Summary', 0, 1);
        $pdf->SetFont('helvetica', '', 12);
        
        $summaryData = [
            'Total Bookings' => $analytics['total_bookings'] ?? 0,
            'Completed Services' => $analytics['completed_bookings'] ?? 0,
            'Pending Services' => $analytics['pending_bookings'] ?? 0,
            'Cancelled Services' => $analytics['cancelled_bookings'] ?? 0,
            'Total Amount Spent' => $analytics['total_spent'] ?? 'KES 0',
            'Average Rating Given' => ($analytics['average_rating'] ?? '0.0') . '/5'
        ];

        foreach ($summaryData as $label => $value) {
            $pdf->Cell(90, 8, $label . ':', 0, 0);
            $pdf->Cell(0, 8, $value, 0, 1);
        }

        // Footer
        $pdf->SetY(-15);
        $pdf->SetFont('helvetica', 'I', 8);
        $pdf->Cell(0, 10, 'Generated by FundiFix - ' . date('Y-m-d H:i:s'), 0, 0, 'C');

        // Output PDF
        $pdf->Output('resident_report_' . date('Y_m_d') . '.pdf', 'D');
        exit;
    }

    public function exportResidentExcel()
    {
        if (!isset($_SESSION['user']) || $_SESSION['user']['role'] !== 'resident') {
            header('Location: ' . $this->baseUrl . '?action=login');
            exit;
        }

        $analytics = $_SESSION['resident_analytics'] ?? [];
        $userName = $_SESSION['user']['name'];

        // Create new Spreadsheet
        $spreadsheet = new Spreadsheet();
        $sheet = $spreadsheet->getActiveSheet();

        // Set document properties
        $spreadsheet->getProperties()
            ->setCreator('FundiFix')
            ->setTitle('Resident Service Report - ' . $userName)
            ->setSubject('Service Usage Analytics');

        // Set headers
        $sheet->setCellValue('A1', 'Resident Service Report');
        $sheet->setCellValue('A2', 'Generated for: ' . $userName);
        $sheet->setCellValue('A3', 'Date: ' . date('F j, Y'));
        
        // Usage Summary
        $sheet->setCellValue('A5', 'Service Usage Summary');
        $sheet->getStyle('A5')->getFont()->setBold(true);
        
        $summaryData = [
            ['Total Bookings', $analytics['total_bookings'] ?? 0],
            ['Completed Services', $analytics['completed_bookings'] ?? 0],
            ['Pending Services', $analytics['pending_bookings'] ?? 0],
            ['Cancelled Services', $analytics['cancelled_bookings'] ?? 0],
            ['Total Amount Spent', $analytics['total_spent'] ?? 'KES 0'],
            ['Average Rating Given', ($analytics['average_rating'] ?? '0.0') . '/5']
        ];

        $row = 6;
        foreach ($summaryData as $data) {
            $sheet->setCellValue('A' . $row, $data[0]);
            $sheet->setCellValue('B' . $row, $data[1]);
            $row++;
        }

        // Auto-size columns
        foreach (range('A', 'B') as $column) {
            $sheet->getColumnDimension($column)->setAutoSize(true);
        }

        // Create Excel file
        $writer = new Xlsx($spreadsheet);
        
        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment;filename="resident_report_' . date('Y_m_d') . '.xlsx"');
        header('Cache-Control: max-age=0');

        $writer->save('php://output');
        exit;
    }
}